pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Get Commit ID') {
            steps {
                script {
                    env.COMMIT_ID = sh(
                        script: 'git rev-parse --short=4 HEAD',
                        returnStdout: true
                    ).trim()

                    echo "Commit ID: ${env.COMMIT_ID}"
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('helloworld') {
                    sh """
                        docker build \
                          -t ghcr.io/srujankn762/hello-world-image:${COMMIT_ID} \
                          .
                    """
                }
            }
        }

        stage('Docker Push') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'ghcr-credentials',
                        usernameVariable: 'GHCR_USER',
                        passwordVariable: 'GHCR_TOKEN'
                    )
                ]) {
                    sh '''
                        echo "$GHCR_TOKEN" | docker login ghcr.io \
                            -u "$GHCR_USER" \
                            --password-stdin

                        docker push ghcr.io/srujankn762/hello-world-image:${COMMIT_ID}

                        docker logout ghcr.io
                    '''
                }
            }
        }
    }

    post {
        success {
            echo "Image pushed successfully:"
            echo "ghcr.io/srujankn762/hello-world-image:${COMMIT_ID}"
        }

        failure {
            echo "Build or push failed."
        }
    }
}